version: '3'

services:
  test_db:
    image: postgres:14
    container_name: test_db
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=auth_test

  fastapi_jwt_auth_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_jwt_auth_test
    depends_on:
      - migrations
      - test_db
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=auth_test
      - PORT=5432
      - HOST=test_db
    command: [ "pytest" ]

  migrations:
    build: .
    container_name: migrations
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=auth_test
      - PORT=5432
      - HOST=test_db
    command: [ "alembic", "upgrade", "head" ]
